### ISSUE TITLE
Support `contentDirectory`

### ISSUE THREAD

**Issue by nicl** [guardian/actions-riff-raff#13]
Riffraff has a feature called `contentDirectory` which overrides the default folder for a deployment's sources. This is not, strictly speaking, necessary, but can help in a few cases:

1. When multiple deployment share the same file (especially if it is large)
2. When multiple deployments share sources from the same directory (e.g. `cdk.out` and multiple stacks)

Some automated tooling, for example, https://github.com/guardian/cdk/pull/1372, uses content directory when generating riff-raff.yaml files.

At the moment, this action provides no support for content directories.

To add it, I propose the following additional input:

**contentDirectories:** a Yaml object containing directory names mapped to sources (supporting the same behaviour for these as `sources` currently provides). E.g.

```
    app: foo
    contentDirectories: |
      upload:
        - cdk.out
        - example.txt
      cdk.out:
        - cdk.out

    config: |
      ...
```

*Note, similar to `config`, because GHA only supports strings for inputs, the `|` is required here.*

In theory this feature could entirely replace `sources` as it enables a superset of its behaviour. (Just name a content directory the same as the deployment to mirror sources).

There are some benefits here:

* defined outside the RR config, which works better with tooling that wants to generate a standard riff-raff.yaml file
* would allow us to deprecate `sources` as it supports the same behaviour

There are downsides too:

* if we deprecate sources, this becomes a breaking change
* if we don't deprecate sources, this duplicates (to some extent) existing functionality
* arguably worse DX for the simple case; `sources` provides a clearer link to the deployment as inlined, as doesn't require duplicating the deployment name

Keen to get thoughts!

cc @akash1810 @jfsoul @philmcmahon

**Comment by akash1810** [comment]
This sounds sensible to me, and I suspect we'd eventually push to remove `sources` to keep the action simple.

Personally, I think `contentDirectory` is a lot clearer in a `riff-raff.yaml` file, as it's more explicit. You have to implicitly know that the Riff-Raff will use the package name as a directory otherwise.

> if we deprecate sources, this becomes a breaking change

I'm not sure this is that bad; there are [24 uses](https://github.com/search?l=YAML&q=org%3Aguardian+actions-riff-raff&type=Code) of this action so far, with the vast majority sitting within DevX services, which we can migrate. Additionally, the current version will continue to exist.

> arguably worse DX for the simple case; sources provides a clearer link to the deployment as inlined, as doesn't require duplicating the deployment name

I somewhat disagree with this. Yes, the DX changes, but we currently still require users to understand the layout of a `riff-raff.yaml` file. Auto-generating the file improves on this, but requires the use of GuCDK.
